server:
  port: 10002 #服务端口

spring:
  application:
    name: config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
         uri: https://github.com/hooray2010/hr-config.git
  rabbitmq: #RabbitMQ相关的配置
    host: 127.0.0.1
    port: 5672
    username: hurui
    password: 123456

management:
  security:
    enabled: false #是否开启actuator安全认证

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://hurui:123456@127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

#logging
logging.config: classpath:logback.xml

#spring data source
spring.datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.106.176.242:3306/cloud?useUnicode=true&characterEncoding=utf-8
        username: alex
        password: Root303!