server:
  port: 10001 #服务端口

spring:
  application:
    name: zuul-server #指定服务名

zuul:
  routes:
    system-app: #这个名字是任意写的
      path: /system-app/** #配置请求URL的请求规则
      #url: http://127.0.0.1:8083 #真正的微服务地址
      serviceId: system-app #指定Eureka注册中心中的服务id
    user-app:
      path: /user-app/**
      serviceId: user-app

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://hurui:123456@127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
  server:
    enable-self-preservation: false #禁用自我保护模式

#logging
logging.config: classpath:logback.xml

#spring data source
spring.datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.106.176.242:3306/cloud?useUnicode=true&characterEncoding=utf-8
        username: alex
        password: Root303!
