server.port: 8081

#order url
hr.order.url: http:127.0.0.1:8082/order/

#logging
logging.config: classpath:logback.xml

#mybatis
mybatis:
  type-aliases-package: com.hr.cloud.entity
  mapper-locations: classpath:mapper/*.xml
  configuration.map-underscore-to-camel-case: true

spring:
  #datasource
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.176.242:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: alex
    password: Root303!
#    url: jdbc:mysql://localhost/localhost_newtank?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root303

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql