server.port: 8081 #服务端口

hr.order.url: http:127.0.0.1:8082/order/ #订单url

#mybatis
mybatis:
  type-aliases-package: com.hr.cloud.entity #entity所在包
  mapper-locations: classpath:mapper/*.xml #sql位置
  configuration.map-underscore-to-camel-case: true #开启驼峰

spring:
  datasource: #datasource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.176.242:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: alex
    password: Root303!

pagehelper: #pagehelper分页插件
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql